### ISSUE TITLE
Checkpoint 'anti_malware+anti_virus' counters being tag=malware tag=attack

### ISSUE THREAD

**Issue by simonsigre** [enosysau/Splunk_TA_checkpoint-opseclea_Enosys#4]
@linsmeyerh it appears the following `counter` style data is being tagged as
`tag=malware tag=attack`when they are just counter events.
Example;
```
opsec:anti_malware	counter
opsec:anti_malware	system
opsec:anti_malware	system(+)counter
opsec:anti_virus	system
opsec:anti_virus	system(+)counter
```
This appears to be filling up `malware` DM acceleration ... not breaking anything .. but just creating a lot of noise that we could optimise.

**Comment by linsmeyerh** [comment]
I have spoken with @Edmund-Tran on Friday and the best approach to resolve this issue is to modify the eventtype configuration:

(current)
[opsec_malware_attack]
search = sourcetype=opsec:anti_virus OR sourcetype=opsec:anti_malware OR (sourcetype=opsec:threat_emulation verdict=Malicious)
#tags = malware attack

(new)
[opsec_malware_attack]
search = sourcetype=opsec:threat_emulation verdict=Malicious
#tags = malware attack

and create a new `stanza` for

[opsec_malware]
search = sourcetype=opsec:anti_virus OR sourcetype=opsec:anti_malware 
#tags = malware

The work above will prevent unwanted tagged `malware attack` logs from being populated into Malware datamodel, and with new `stanza` still being able to search for malware tagged logs.

Please let me know if you approve the above and I will apply the changes to COG search heads and push the changes to our TA `Splunk_TA_checkpoint-opseclea_Enosys` as part of a new version to be released.

**Comment by simonsigre** [comment]
@linsmeyerh yes please correct these however is required and push to repo

**Comment by linsmeyerh** [comment]
Work has been performed and changes pushed to repo. If you are ok we can close this case.
